import json
import requests
import argparse
import os
import subprocess

def fetch_cdn_ips(cdn_type):
    """
    Fetches IP prefixes for a specified CDN service (CloudFront or Cloudflare).
    Returns a list of IP prefixes.
    """
    ip_prefixes = []
    json_url = ""
    try:
        if cdn_type == 'cloudfront':
            json_url = 'https://ip-ranges.amazonaws.com/ip-ranges.json'

            print(f"Downloading IP ranges from {json_url}")
            response = requests.get(json_url)
            response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)
            data = response.json()
            
            # Extract IPv4 prefixes
            if 'prefixes' in data:
                for prefix in data['prefixes']:
                    if prefix.get('service') == 'CLOUDFRONT':
                        ip_prefixes.append(prefix['ip_prefix'])

            # Extract IPv6 prefixes
            if 'ipv6_prefixes' in data:
                for prefix in data['ipv6_prefixes']:
                    if prefix.get('service') == 'CLOUDFRONT':
                        ip_prefixes.append(prefix['ipv6_prefix'])

        elif cdn_type == 'cloudfront-origin-shield':
            json_url = 'https://ip-ranges.amazonaws.com/ip-ranges.json'

            print(f"Downloading IP ranges from {json_url}")
            response = requests.get(json_url)
            response.raise_for_status()  # Raise an HTTPError for bad responses (4xx or 5xx)
            data = response.json()
            
            # Extract IPv4 prefixes
            if 'prefixes' in data:
                for prefix in data['prefixes']:
                    if prefix.get('service') == 'CLOUDFRONT_ORIGIN_FACING':
                        ip_prefixes.append(prefix['ip_prefix'])

            # Extract IPv6 prefixes
            if 'ipv6_prefixes' in data:
                for prefix in data['ipv6_prefixes']:
                    if prefix.get('service') == 'CLOUDFRONT_ORIGIN_FACING':
                        ip_prefixes.append(prefix['ipv6_prefix'])

        elif cdn_type == 'cloudflare':
            ipv4_url = "https://www.cloudflare.com/ips-v4"
            ipv6_url = "https://www.cloudflare.com/ips-v6"

            print(f"Downloading IPv4 ranges from {ipv4_url}")
            ipv4_response = requests.get(ipv4_url)
            ipv4_response.raise_for_status()
            ipv4_prefixes = ipv4_response.text.strip().split('\n')

            print(f"Downloading IPv6 ranges from {ipv6_url}")
            ipv6_response = requests.get(ipv6_url)
            ipv6_response.raise_for_status()
            ipv6_prefixes = ipv6_response.text.strip().split('\n')

            ip_prefixes = ipv4_prefixes + ipv6_prefixes
        else:
            print(f"Error: Unknown CDN type '{cdn_type}'. Supported types are 'cloudfront', 'cloudfront-origin-shield' and 'cloudflare'.")
            return None

    except requests.exceptions.RequestException as e:
        print(f"Error: Could not download data. {e}")
        return None
    except json.JSONDecodeError as e:
        print(f"Error: Could not decode JSON. {e}")
        return None

    return ip_prefixes

def write_to_file(ip_prefixes, output_path):
    try:
        with open(output_path, 'w') as f:
            for ip in ip_prefixes:
                f.write(f"{ip}\n")
        print(f"Successfully wrote {len(ip_prefixes)} IPs to {output_path}")
    except IOError as e:
        print(f"Error writing to file {output_path}: {e}")

def write_nginx_realip(ip_prefixes, output_path, header):
    try:
        directory = os.path.dirname(output_path)
        if directory:
            os.makedirs(directory, exist_ok=True)
        
        with open(output_path, 'w') as f:
            f.write(f"# Generated by cdn_origin_ranges.py\n\n")
            for ip in ip_prefixes:
                f.write(f"set_real_ip_from {ip};\n")
            f.write(f"\nreal_ip_header {header};\n")
        print(f"Successfully wrote Nginx RealIP config to {output_path}")
    except IOError as e:
        print(f"Error writing to file {output_path}: {e}")

def write_nginx_whitelist(ip_prefixes, output_path, variable_name):
    try:
        directory = os.path.dirname(output_path)
        if directory:
            os.makedirs(directory, exist_ok=True)

        with open(output_path, 'w') as f:
            f.write(f"# Generated by cdn_origin_ranges.py\n\n")
            f.write(f"geo $realip_remote_addr ${variable_name} {{\n")
            f.write(f"    default 0;\n")
            for ip in ip_prefixes:
                f.write(f"    {ip} 1;\n")
            f.write(f"}}\n")
        print(f"Successfully wrote Nginx Whitelist config to {output_path}")
    except IOError as e:
        print(f"Error writing to file {output_path}: {e}")

def reload_nginx():
    try:
        print("Testing Nginx configuration...")
        subprocess.run(['nginx', '-t'], check=True)
        print("Reloading Nginx...")
        subprocess.run(['systemctl', 'reload', 'nginx'], check=True)
        print("Nginx reloaded successfully.")
    except subprocess.CalledProcessError as e:
        print(f"Error reloading Nginx: {e}")
    except FileNotFoundError:
        print("Error: nginx or systemctl command not found. Ensure Nginx is installed and you are running as root.")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Download and extract CDN IP ranges, and optionally generate Nginx configs.")
    parser.add_argument('--cdn',
                        choices=['cloudfront', 'cloudflare', 'cloudfront-origin-shield'],
                        required=True,
                        help="Specify the CDN provider to download IP ranges for.")
    parser.add_argument('--output',
                        default=None,
                        help="Optional: Specify the output text file name. Defaults to '<cdn_type>_origin_ips.txt'.")
    parser.add_argument('--nginx-realip',
                        help="Optional: Path to output Nginx RealIP configuration file.")
    parser.add_argument('--nginx-whitelist',
                        help="Optional: Path to output Nginx Whitelist (geo) configuration file.")
    parser.add_argument('--reload',
                        action='store_true',
                        help="Optional: Reload Nginx after generating configurations.")

    args = parser.parse_args()

    ip_prefixes = fetch_cdn_ips(args.cdn)

    if ip_prefixes:
        # Default text output if no specific config is requested or if output is explicitly provided
        if args.output:
            write_to_file(ip_prefixes, args.output)
        elif not args.nginx_realip and not args.nginx_whitelist:
            output_file_name = f"{args.cdn}_origin_ips.txt"
            write_to_file(ip_prefixes, output_file_name)
        
        # Determine headers and variables based on CDN
        if 'cloudflare' in args.cdn:
            header = "CF-Connecting-IP"
            variable_name = "cloudflare_ip"
        else:
            header = "X-Forwarded-For"
            variable_name = "cloudfront_ip"

        if args.nginx_realip:
            write_nginx_realip(ip_prefixes, args.nginx_realip, header)
        
        if args.nginx_whitelist:
            write_nginx_whitelist(ip_prefixes, args.nginx_whitelist, variable_name)

        if args.reload:
            reload_nginx()
